"""remove_embedding_from_document

Revision ID: 3a79d096f9fd
Revises: cc4f2e24776d
Create Date: 2025-12-03 11:22:03.594719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3a79d096f9fd'
down_revision: Union[str, Sequence[str], None] = 'cc4f2e24776d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
        dim=1536), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
