"""Initial SaaS Schema

Revision ID: 5d8b31599dec
Revises: 
Create Date: 2025-12-04 19:53:52.217481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '5d8b31599dec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_embeddings',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('metadata', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('node_id', sa.String(), nullable=True),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1536), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tenants',
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('slug', sa.String(length=50), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('chatbots',
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('public_id', sa.String(
                        length=64), nullable=False),
                    sa.Column('allowed_domains', postgresql.ARRAY(
                        sa.String()), nullable=False),
                    sa.Column('encrypted_openai_key',
                              sa.String(), nullable=True),
                    sa.Column('encrypted_llama_cloud_key',
                              sa.String(), nullable=True),
                    sa.Column('rag_config', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('widget_config', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_chatbots_id'), 'chatbots', ['id'], unique=False)
    op.create_index(op.f('ix_chatbots_public_id'),
                    'chatbots', ['public_id'], unique=True)
    op.create_index(op.f('ix_chatbots_tenant_id'),
                    'chatbots', ['tenant_id'], unique=False)
    op.create_table('conversations',
                    sa.Column('chatbot_id', sa.UUID(), nullable=False),
                    sa.Column('visitor_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('summary', sa.String(length=255), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_conversations_chatbot_id'),
                    'conversations', ['chatbot_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'),
                    'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_visitor_id'),
                    'conversations', ['visitor_id'], unique=False)
    op.create_table('documents',
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.Column('chatbot_id', sa.UUID(), nullable=False),
                    sa.Column('filename', sa.String(
                        length=255), nullable=False),
                    sa.Column('file_url', sa.String(
                        length=1024), nullable=False),
                    sa.Column('file_size', sa.Integer(), nullable=False),
                    sa.Column('file_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('error_message', sa.String(), nullable=True),
                    sa.Column('metadata_map', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_documents_chatbot_id'),
                    'documents', ['chatbot_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_status'),
                    'documents', ['status'], unique=False)
    op.create_table('messages',
                    sa.Column('conversation_id', sa.UUID(), nullable=False),
                    sa.Column('role', sa.Enum('USER', 'ASSISTANT',
                              'SYSTEM', name='messagerole'), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('sources', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('tokens_used', sa.Integer(), nullable=False),
                    sa.Column('rating', sa.Boolean(), nullable=True),
                    sa.Column('feedback_text', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                                            'conversations.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_messages_conversation_id'),
                    'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_chatbot_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_visitor_id'),
                  table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_chatbot_id'),
                  table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_chatbots_tenant_id'), table_name='chatbots')
    op.drop_index(op.f('ix_chatbots_public_id'), table_name='chatbots')
    op.drop_index(op.f('ix_chatbots_id'), table_name='chatbots')
    op.drop_table('chatbots')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('data_embeddings')
    # ### end Alembic commands ###
