"""create rag_configs table

Revision ID: a5b63a8cbcf8
Revises: d49a287748c5
Create Date: 2025-12-11 13:22:07.334468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5b63a8cbcf8'
down_revision: Union[str, Sequence[str], None] = 'd49a287748c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_configs',
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_configs_chatbot_id'), 'rag_configs', ['chatbot_id'], unique=True)
    op.create_index(op.f('ix_rag_configs_id'), 'rag_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_configs_id'), table_name='rag_configs')
    op.drop_index(op.f('ix_rag_configs_chatbot_id'), table_name='rag_configs')
    op.drop_table('rag_configs')
    # ### end Alembic commands ###
