"""Move API keys from Chatbot to Tenant

Revision ID: c92e38363433
Revises: 5d8b31599dec
Create Date: 2025-12-04 20:08:41.478781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92e38363433'
down_revision: Union[str, Sequence[str], None] = '5d8b31599dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'encrypted_openai_key')
    op.drop_column('chatbots', 'encrypted_llama_cloud_key')
    op.add_column('tenants', sa.Column('encrypted_openai_key', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('encrypted_llama_cloud_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'encrypted_llama_cloud_key')
    op.drop_column('tenants', 'encrypted_openai_key')
    op.add_column('chatbots', sa.Column('encrypted_llama_cloud_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chatbots', sa.Column('encrypted_openai_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
