"""first build

Revision ID: cc4f2e24776d
Revises: 
Create Date: 2025-12-03 11:03:21.741257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'cc4f2e24776d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('api_key', sa.String(
                        length=1024), nullable=True),
                    sa.Column('allowed_domains', sa.JSON(), nullable=True),
                    sa.Column('widget_config', sa.JSON(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('api_key')
                    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('conversation',
                    sa.Column('client_id', sa.UUID(), nullable=False),
                    sa.Column('end_user_id', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_conversation_client_id'),
                    'conversation', ['client_id'], unique=False)
    op.create_index(op.f('ix_conversation_end_user_id'),
                    'conversation', ['end_user_id'], unique=False)
    op.create_index(op.f('ix_conversation_id'),
                    'conversation', ['id'], unique=False)
    op.create_table('document',
                    sa.Column('client_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('content_hash', sa.String(), nullable=True),
                    sa.Column('metadata_map', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1536), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_document_client_id'),
                    'document', ['client_id'], unique=False)
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_table('conversation_document',
                    sa.Column('conversation_id', sa.UUID(), nullable=True),
                    sa.Column('document_id', sa.UUID(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                                            'conversation.id'], ),
                    sa.ForeignKeyConstraint(
                        ['document_id'], ['document.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_conversation_document_conversation_id'),
                    'conversation_document', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_document_document_id'),
                    'conversation_document', ['document_id'], unique=False)
    op.create_index(op.f('ix_conversation_document_id'),
                    'conversation_document', ['id'], unique=False)
    op.create_table('message',
                    sa.Column('conversation_id', sa.UUID(), nullable=True),
                    sa.Column('content', sa.String(), nullable=True),
                    sa.Column('role', postgresql.ENUM('user', 'assistant',
                                                      'system', name='MessageRoleEnum'), nullable=True),
                    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCESS',
                                                        'ERROR', name='MessageStatusEnum'), nullable=True),
                    sa.Column('rating', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                                            'conversation.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_message_conversation_id'),
                    'message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_table('message_sub_process',
                    sa.Column('message_id', sa.UUID(), nullable=True),
                    sa.Column('source', postgresql.ENUM('CHUNKING', 'NODE_PARSING', 'EMBEDDING', 'LLM', 'QUERY', 'RETRIEVE', 'SYNTHESIZE', 'TREE', 'SUB_QUESTION', 'TEMPLATING',
                              'FUNCTION_CALL', 'RERANKING', 'EXCEPTION', 'AGENT_STEP', 'CONSTRUCTED_QUERY_ENGINE', 'SUB_QUESTIONS', name='MessageSubProcessSourceEnum'), nullable=True),
                    sa.Column('status', postgresql.ENUM('PENDING', 'FINISHED',
                                                        name='MessageSubProcessStatusEnum'), nullable=False),
                    sa.Column('metadata_map', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_message_sub_process_id'),
                    'message_sub_process', ['id'], unique=False)
    op.create_index(op.f('ix_message_sub_process_message_id'),
                    'message_sub_process', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_sub_process_message_id'),
                  table_name='message_sub_process')
    op.drop_index(op.f('ix_message_sub_process_id'),
                  table_name='message_sub_process')
    op.drop_table('message_sub_process')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_conversation_document_id'),
                  table_name='conversation_document')
    op.drop_index(op.f('ix_conversation_document_document_id'),
                  table_name='conversation_document')
    op.drop_index(op.f('ix_conversation_document_conversation_id'),
                  table_name='conversation_document')
    op.drop_table('conversation_document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_index(op.f('ix_document_client_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_conversation_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_end_user_id'),
                  table_name='conversation')
    op.drop_index(op.f('ix_conversation_client_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
