"""add selected_rag_config_id to chatbots

Revision ID: d49a287748c5
Revises: a56dd038fe22
Create Date: 2025-12-11 12:51:10.149878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd49a287748c5'
down_revision: Union[str, Sequence[str], None] = 'a56dd038fe22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'rag_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('rag_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
